// <auto-generated />
namespace Uni.Educational.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ForeignKeyes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ForeignKeyes));
        
        string IMigrationMetadata.Id
        {
            get { return "201609072320526_ForeignKeyes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
